### ISSUE TITLE
how to use 'models/embedding-gecko-001'

### ISSUE THREAD

**Issue by laocan** [google/generative-ai-docs#254]
### Description of the feature request:

I try it in this way ( similar to the usage of 'models/embedding-001' ) 
`res_emb = genai.embed_content(model='models/embedding-gecko-001',
                              content=' ... ',
                              task_type='RETRIEVAL_DOCUMENT',
                              title='emb by gecko')
res_emb`

but it reports error:
`NotFound: 404 POST https://generativelanguage.googleapis.com/v1beta/models/embedding-gecko-001:embedContent?%24alt=json%3Benum-encoding%3Dint: models/embedding-gecko-001 is not found for API version v1beta, or is not supported for embedContent. Call ListModels to see the list of available models and their supported methods.`

Can I use 'models/embedding-gecko-001' for embedding ?

**Comment by ymodak** [comment]
Hi @laocan, 
Thanks for your issues. This failure is due to a limitation in `supported_generation_methods=['embedText', 'countTextTokens']` in `'models/embedding-001'`.
```python
import google.generativeai as genai
for m in genai.list_models():
  if 'gecko' in m.name:
    print(m)
```
output -
```
Model(name='models/embedding-gecko-001',
      base_model_id='',
      version='001',
      display_name='Embedding Gecko',
      description='Obtain a distributed representation of a text.',
      input_token_limit=1024,
      output_token_limit=1,
      supported_generation_methods=['embedText', 'countTextTokens'],
      temperature=None,
      top_p=None,
      top_k=None)
```

Also see https://ai.google.dev/tutorials/rest_quickstart#embedding which explicitly calls out using the `embedding-001` model with either `embedContents` or `batchEmbedContents`.
