### ISSUE TITLE
Gemma get_started.ipynb has install version error

### ISSUE THREAD

**Issue by Annie29** [google/generative-ai-docs#404]
### Description of the bug:

When running the install step 
!pip install -q -U keras-nlp
!pip install -q -U keras>=3 
in site/en/gemma/docs/get_started.ipynb, I get the error:

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tf-keras 2.15.1 requires tensorflow<2.16,>=2.15, but you have tensorflow 2.16.1 which is incompatible.

### Actual vs expected behavior:

Actual is error shown above; expected is no error.

### Any other information you'd like to share?

This was run on Colab

_No response_

**Comment by singhniraj08** [comment]
@Annie29, The error is because of dependency issues and can be ignored. The notebook should run without any issues. Please let us know if you faces any issues running the [notebook](https://colab.research.google.com/github/google/generative-ai-docs/blob/main/site/en/gemma/docs/get_started.ipynb). Thank you!
