### ISSUE TITLE
 WebBaseLoader data type error

### ISSUE THREAD

**Issue by atmikshetty** [google/generative-ai-docs#436]
### Description of the bug:

File where the issue exists: examples/gemini/python/langchain/Gemini_LangChain_Summarization_WebLoad.ipynb

Code Snippet:
stuff_chain = (
    # Extract data from the documents and add to the key `text`.
    {
        "text": lambda docs: "\n\n".join(
            format_document(doc, doc_prompt) for doc in docs
        )
    }
    | llm_prompt         # Prompt for Gemini
    | llm                # Gemini function
    | StrOutputParser()  # output parser
)

throws an data type error when accessing the data from the docs.

### Actual vs expected behavior:

Actual: The chain does not building since the dict data type is not directly accepted.
Expected: The chain should be successfully created.

![image](https://github.com/google/generative-ai-docs/assets/109427822/9d4971ab-e6eb-47fa-873c-2e8b5f0b471b)

### Any other information you'd like to share?

This could be resolved by using a text_splitter. I can make a pr resolving this issue if it's possible. Do reply.

**Comment by singhniraj08** [comment]
@atmikshetty, Hi, I don't see any issues running the Langchain example tutorial. Ref: Screenshot below
Can you please share the replicate colab gist so that we can reproduce the code on our end. Thank you!

![image](https://github.com/google/generative-ai-docs/assets/110809167/2196a7b3-a846-468b-9a3d-03df00068d31)
